version: "3"

services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - 9540:9540
    volumes:
      - upload:/usr/share/nginx/html/static
    depends_on:
      - servers

  servers:
    build:
      context: ./server
    restart: always
    ports:
      - 3001:3001
    volumes:
      - upload:/upload
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'know'
    volumes:
      - mysql:/var/lib/mysql
      - ./db/know.sql:/docker-entrypoint-initdb.d/know.sql


volumes:
  mysql:
  redis:
  upload:
