# 开发环境配置
app:
    prefix: '/api'
    port: 3001
    logger:
        # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
        dir: '../logs'
    # 文件相关
    file:
        # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
        location: '../upload'
        # 文件服务器地址，这是开发环境的配置 生产环境请自行配置成可访问域名
        domain: 'http://localhost:3001'
        # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8081/static/****.jpg  , 如果不需要则 设置 ''
        serveRoot: '/static'
# 数据库配置
db:
    mysql:
        host: 'localhost'
        username: 'root'
        password: '123456'
        database: 'know-test'
        port: 3306
        charset: 'utf8mb4'
        logger: 'advanced-console'
        logging: true
        multipleStatements: true
        dropSchema: false
        synchronize: true
        supportBigNumbers: true
        bigNumberStrings: true

# redis 配置
redis:
    host: 'localhost'
    port: 6379
    db: 0
    keyPrefix: 'nest:'

# jwt 配置
jwt:
    secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
    expiresin: '7d'
    refreshExpiresIn: '14d'

email:
    transport:
        # 邮箱服务器地址
        host: 'smtp.qq.com'
        # 服务器端口 默认 465
        port: 465
        auth:
            # 用户邮箱
            user: 'ymzdjiang@qq.com'
            # 授权码
            pass: 'filbvwhjyrtsdige'
    # 是否开启预览，开启了这个属性，在调试模式下会自动打开一个网页，预览邮件
    preview: false
    defaults:
        from: '知迹 <ymzdjiang@qq.com>'

session:
    secret: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
    name: 'session'
